### ISSUE TITLE
issue when running script

### ISSUE THREAD

**Issue by stevewas** [rootflags/tis-clone#1]
Hello,

I'm trying to run the script but it doesn't seem to download the XHTML files.

when trying to run 1 script manually with the land rover demo id I get this error

mismatched tag at line 54, column 3, byte 810 at /usr/lib/x86_64-linux-gnu/perl5/5.30/XML/Parser.pm line 187.
XML::Simple called at /tis-clone/scripts/toc2html line 11.

script ran /tis-clone/scripts/dl-html-bm.sh 27J0U

verified that I have all the required modules installed

**Comment by stevewas** [comment]
it was an issue with my cookies. I used a chrome plugin to export then into netscape format and it worked now.

**Comment by xantari** [comment]
I'm also getting this issue, but I already have mine in netscape format...
